### ISSUE TITLE
file not available

### ISSUE THREAD

**Issue by Priyanka-VLSI** [sumanth-kalluri/cnn_hardware_acclerator_for_fpga#1]
c_shift_ram file is not available in the source folder.

**Comment by sumanth-kalluri** [comment]
The c_shift_ram is an ip from xilinx that was instantiated for better results. There is no separate .v file available for it owing to how vivado handles ip generation. I suggest you synthesize one for yourself on whatever target device you're working on and whatever tool you're using. 

It is only a shift register so it should not be hard to manage.
