### ISSUE TITLE
where is the module c_shift_ram_0 in convolver？

### ISSUE THREAD

**Issue by wayneszc** [sumanth-kalluri/cnn_hardware_acclerator_for_fpga#4]
hello，I want to ask where is the module c_shift_ram_0 in convolver？ thanks！

**Comment by sumanth-kalluri** [comment]
Hi
c_shift_ram_0 is a basic shift register and was synthesized directly by vivado (the software I had used for the project). No separate .v file was created so I could not upload it.

I believe it is quite easy for you to synthesize it yourself no matter which software you're using.
