### ISSUE TITLE
About the txt

### ISSUE THREAD

**Issue by wangj346** [sumanth-kalluri/cnn_hardware_acclerator_for_fpga#5]
hello , i am very interested in your job. But when i run the project in Vivado , i find the ip_data.txt and tb_op.txt missing. If the files can be shared will be appreciated.

**Comment by sumanth-kalluri** [comment]
@wangj346 these are the files written by scripts. ip_data.txt is the input data text file generated by the python script checker_acclerator.py and TB_OP.TXT is written by the testbench. Run these scripts and you'll have the files.
